config/routes.rb
Rails.application.routes.draw do

  get 'pages/dashboard'
  get 'pages/become_admin'
  get 'pages/become_visit'
  delete 'pages/delete_user'

	resources :posts do
		resources :comments, only: [:create, :destroy]
	end

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations'
	}

	root 'posts#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= link_to "#{user.name}", root_path%></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Admin', pages_become_admin_path(user), class: 'btn btn-sm btn-success' %></td>
        <td><%= link_to 'visit', pages_become_visit_path(user), class: 'btn btn-sm btn-danger' %></td>
        <td>
          <% if can?(:destroy, user)%>

          <%= link_to 'eliminar', pages_delete_user_path(user),  method: :delete, data: {confirm: 'estas seguo de querer eliminar el usuario'}, class: 'btn btn-sm btn-danger' %>
          <% end %>
        </td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>
s
<%= link_to 'volver', root_path, class: 'btn btn-primary' %>